### ISSUE TITLE
Please mark this lib as limited function or alpha quality, it doesn't work

### ISSUE THREAD

**Issue by Tafnab** [arbitrary-precision/ap#6]
ap_uint<512> prev{"0xeeeb0b091e506a4f8da7629f0b98274bbb665398af6a3b588e6763c97919956"};
	cout << "prev = " << prev.str(2) << endl;

produces zero output under gnu c++, std=c++17.  Also, if you try to set the variable using string literal constants, g++ complains they are too large (which is true). I've tried multiple variants on this theme.  It simply can't deal with large numbers, which was the point. 

Nice design concept for the lib, but it doesn't work, and I've wasted a bunch of time trying to figure out why.  You should save other people the trouble.  The trouble seems to be with initializing the large integers.

**Comment by deohayer** [comment]
> produces no output under gnu c++, std=c++17

From the README: 

> Hexadecimal strings are always uppercase, be it initialization or output. You can specify string "0123456789abcdef" if you want lowercase.

The function:

- encounters the very first 'e' character,
- fails to interpret it as a digit (because it is lowercase)
- returns without proceeding further, with the parsed value 0.

From the functionality perspective, everything is just fine:

```
#include "ap.hpp"
#include <iostream>
#include <iomanip>

#define LOWERCASE "0123456789abcdef"

int main() {
    // Hex to binary.
    ap_uint<512> prev{"0xeeeb0b091e506a4f8da7629f0b98274bbb665398af6a3b588e6763c97919956", 0, LOWERCASE};
    std::cout << "prev = " << prev.str(2) << std::endl;
    // Binary to hex, copy-pasted from the command line.
    ap_uint<512> prevb{"0b111011101110101100001011000010010001111001010000011010100100111110001101101001110110001010011111000010111001100000100111010010111011101101100110010100111001100010101111011010100011101101011000100011100110011101100011110010010111100100011001100101010110"};
    std::cout << "prevb = " << prevb.str(16, LOWERCASE) << std::endl;
    // Cross-check the values.
    std::cout << std::boolalpha << (prev.str(2) == prevb.str(2)) << std::endl;
    std::cout << std::boolalpha << (prev.str(16, LOWERCASE) == prevb.str(16, LOWERCASE)) << std::endl;
    return 0;
}
```
Produces:
```
~/ws/ap$ g++ --std=c++17 a.cpp
~/ws/ap$ ./a.out 
prev = 0b111011101110101100001011000010010001111001010000011010100100111110001101101001110110001010011111000010111001100000100111010010111011101101100110010100111001100010101111011010100011101101011000100011100110011101100011110010010111100100011001100101010110
prevb = 0xeeeb0b091e506a4f8da7629f0b98274bbb665398af6a3b588e6763c97919956
true
true
```

> if you try to set the variable using string literal constants
I assume you mean:
```
ap_uint<512> prev = 0xeeeb0b091e506a4f8da7629f0b98274bbb665398af6a3b588e6763c97919956;
```
Integer literals are built-in and have predefined boundaries. Best I can do is to define a user-defined literal (let's say, "_ap"). The initialization will look like:
```
ap_uint<512> prev = 0xeeeb0b091e506a4f8da7629f0b98274bbb665398af6a3b588e6763c97919956_ap;
```
This has no benefits other than nice highlighting in an IDE, so why bother.

**Comment by Tafnab** [comment]
OK, you got your star back.  I had to come back to this project anyway because I was having even more trouble with GMP.

It really wasn't obvious from the instructions that the initialization would fail in lowercase. The initialization should probably fail loudly instead of failing silently.  I couldn't figure out why it stopped. I will just switch to uppercase.

Having an _AP or _ap literal would be fantastic from a code readability standpoint.  Also, think about if you have to assign new large numbers to an ap_uint.  The literal would be much more convenient.

Once again, congratulations on the library design.

Can I make a feature request?: .reverse_digits(base) and .reverse_bytes()  

I haven't found an arb. precision lib yet that can do it, unless you secretly have these functions.

**Comment by deohayer** [comment]
> The initialization should probably fail loudly instead of failing silently

This is better to be configurable. I cannot use exceptions, because they are not always good - AOSP, for example, disables exceptions as a language feature by default.

> Can I make a feature request?: .reverse_digits(base) and .reverse_bytes()

Unfortunately, I do not have time to implement new features, and these two are too specific anyway. Use the string manipulations instead: cast to string - do the stuff - cast to int.
